### ISSUE TITLE
League position for drawn teams should be based on game points

### ISSUE THREAD

**Issue by antoinepetty** [srobo/livestream-overlay#7]
Incorrect
![image](https://user-images.githubusercontent.com/36314396/87876044-24236700-c9cd-11ea-8be7-5d1cc3828640.png)

Correct
![image](https://user-images.githubusercontent.com/36314396/87876048-300f2900-c9cd-11ea-9db7-5d197d1c78c6.png)

**Comment by trickeydan** [comment]
Not that clear what you want here? Please could you explain exactly which points you want to show, and how the teams are sorted?
